version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./app.Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
